CREATE TABLE treatment_task (
    id INT PRIMARY KEY NOT NULL,
    action VARCHAR(10) NOT NULL,
    patient VARCHAR(50) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    status VARCHAR(10) NOT NULL
);

CREATE SEQUENCE TREATMENT_TASK_SEQ INCREMENT BY 50;
